# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       smem

# >> macros
# << macros

Summary:    Reports physical memory usage
Version:    1.5
Release:    6
Group:      Applications/System
License:    GPLv2
URL:        https://www.selenic.com/smem/
Source0:    %{name}-%{version}.tar.bz2
Source100:  smem.yaml
Patch0:     SFOS.patch
Patch1:     autotoolify.patch
Requires:   python3-base
BuildRequires:  autoconf
BuildRequires:  automake
Provides:   openrepos-smem = %{version}-%{release}
Obsoletes:   openrepos-smem < %{version}

%description
smem is a tool that can give numerous reports on memory usage on Linux
systems. Unlike existing tools, smem can report proportional set size
(PSS), which is a more meaningful representation of the amount of
memory used by libraries and applications in a virtual memory system.

%if "%{?vendor}" == "chum"
Type: console-application
PackagerName: nephros
DeveloperName: Matt Mackall
Categories:
 - System
Custom:
  PackagingRepo: http://gitlab.com/sailfishos-chum/smem
Url:
  Homepage: https://www.selenic.com/smem/
%endif


%prep
%setup -q -n %{name}-%{version}

# SFOS.patch
%patch0 -p1
# autotoolify.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
autoreconf --install
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
install -D -m 755 smem %{buildroot}/%{_bindir}/smem
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/smem
%{_bindir}/smemcap
# >> files
# << files
